---
- name: ansible tasks
  hosts: workstation  
  become: true
  vars:
    source_folder_path: "/home/student/temp"  
    file_pattern: "myfile.txt"  
    dest_folder: "/home/student/"  

  tasks:
  
    - block:
        - name: creating temporary directory on workstation
          ansible.builtin.file:
            path: "{{ dest_folder }}"
            state: directory

        - name: ensuring internal work dir exists on workstation
          ansible.builtin.file:
            path: "{{ dest_folder }}"
            state: directory

      rescue:
        - name: error
          ansible.builtin.fail:
            msg: "directory creation failed with RC: {{ ansible_failed_result.rc }}"

    - block:
        - name: ensuring the file is readable on bastion
          ansible.builtin.file:
            path: "{{ source_folder_path }}/{{ file_pattern }}"
            mode: '444'  
          delegate_to: bastion

        - name: checking if the file exists on bastion or not
          ansible.builtin.command:
            cmd: "ls -l {{ source_folder_path }}/{{ file_pattern }}"
          delegate_to: bastion
          register: bastion_file_check
          ignore_errors: yes

        - name: fails if file does not exist on bastion
          ansible.builtin.fail:
            msg: "file not found on bastion: {{ source_folder_path }}/{{ file_pattern }}"
          when: bastion_file_check.rc != 0

        - name: fetching file from bastion to workstation
          ansible.builtin.fetch:
            src: "{{ source_folder_path }}/{{ file_pattern }}"
            dest: "{{ dest_folder }}/"  
            flat: true  
          delegate_to: bastion

      rescue:
        - name: error
          ansible.builtin.fail:
            msg: "failed to fetch file from bastion with RC: {{ ansible_failed_result.rc }}"
  
    - block:
        - name: list contents of the destination folder for verification
          ansible.builtin.command:
            cmd: ls -l "{{ dest_folder }}/"
          register: dir_contents

        - name: fails if the fetched file does not exist in workstation directory
          ansible.builtin.fail:
            msg: "Fetched file not found in workstation directory"
          when: "'myfile.txt' not in dir_contents.stdout"

        - name: checking if the file exists on workstation
          ansible.builtin.stat:
            path: "{{ dest_folder }}/{{ file_pattern }}"
          register: file_check

        - name: Set fact if file exists
          ansible.builtin.set_fact:
            file_exists: "{{ file_check.stat.exists }}"
        
        - name: uploading file to all servers if file exists
          ansible.builtin.copy:
            src: "{{ dest_folder }}/{{ file_pattern }}"
            dest: "/home/student/{{ file_pattern }}"
            force: yes  
          delegate_to: "{{ item }}"
          loop: "{{ groups['servers'] }}"
          when: file_exists

      rescue:
        - name: error
          ansible.builtin.fail:
            msg: "no file found on workstation with RC: {{ ansible_failed_result.rc }}"
